name: deploy to gh-pages

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: verify tag
        run: git branch --contains $GITHUB_SHA | sed -e 's/^[ \t *]*//' | grep '^master$'

      - name: setup env
        run: |
          docker build -t mew-build-container .
          echo ::set-env name=NODE_VERSION::$(docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "node --version")

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-

      - name: npm install
        run: docker run --rm -v `pwd`:/home:rw --user "$(id -u):$(id -g)" mew-build-container /bin/bash -c "npm install"

      - name: build
        run: docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "npm run build:hash"

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.MEW_BOT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
